In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
get_ipython().magic('pylab inline')
#get_ipython().magic('matplotlib auto')

#pylab.rcParams['figure.figsize'] = (12, 8)
#import sys

Populating the interactive namespace from numpy and matplotlib


In [2]:
df = pd.read_csv('input/train_20percent.csv',encoding = 'ISO-8859-1')
df = df.drop(["last_date_primary", "spouse_idx"], axis=1)
df['age']   = pd.to_numeric(df['age'], errors='coerce')
df['seniority']   = pd.to_numeric(df['seniority'], errors='coerce')
#remove negative seniority
df=df[df['seniority']>0]
#save original df as df_save
df_raw = df

C:\Users\WHsieh\AppData\Local\Continuum\Anaconda2\lib\site-packages\IPython\core\interactiveshell.py:2717: DtypeWarning: Columns (5,8,11,15) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [3]:
#"isnull()" is a function that checks if something is NaN or empty. 
#The "~" (tilde) operator negates the following expression. 
#So we are saying give me a dataframe from your original dataframe but only where the 'data' rows are NOT null.
df = df[~df.isnull()]

In [4]:
#df_now[df_now.isnull()]
#df_now.head(10)
df.isnull().sum()


date                            0
id                              0
employee_index                  0
country_residence               0
sex                            16
age                             0
first_join_date                 0
new_customer_index              0
seniority                       0
primary                         0
customer_type                  35
customer_relation              35
residence_idx                   0
foreigner_idx                   0
channel                      5076
deceased                        0
address                         0
province_code               13199
province_name               13199
activity_idx                    0
gross_income               533846
segment                      5902
saving_account                  0
guarantees                      0
current_account                 0
derivada_account                0
payroll_account                 0
junior_account                  0
mas_particular_account          0
particular_acc

In [5]:
df.head(0)
for field in ['customer_type','customer_relation']:
    print(df[field].unique())


[1.0 2.0 3.0 u'1.0' u'1' u'2.0' u'2' u'3.0' nan u'3']
[u'A' u'I' u'P' nan]


In [6]:
#dropna can remove nan, isnull finds NaN, empty
df = df.dropna(axis=0)
df.head()
df.isnull().sum()
df_clean = df

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2158888 entries, 0 to 2729459
Data columns (total 46 columns):
date                       object
id                         int64
employee_index             object
country_residence          object
sex                        object
age                        float64
first_join_date            object
new_customer_index         float64
seniority                  float64
primary                    float64
customer_type              object
customer_relation          object
residence_idx              object
foreigner_idx              object
channel                    object
deceased                   object
address                    float64
province_code              float64
province_name              object
activity_idx               float64
gross_income               float64
segment                    object
saving_account             int64
guarantees                 int64
current_account            int64
derivada_account           int64


In [8]:
feature_cols =['date', 'id', 'employee_index', 'country_residence', 'sex', 'age',
       'first_join_date', 'new_customer_index', 'seniority', 'primary',
       'customer_type', 'customer_relation', 'residence_idx', 'foreigner_idx',
       'channel', 'deceased', 'address', 'province_code', 'province_name',
       'activity_idx', 'gross_income', 'segment']
for ind, feature_col in enumerate(feature_cols):
    uniq_values = df[feature_col].unique()
    print(feature_col,uniq_values,len(uniq_values))

('date', array([u'2015-01-28', u'2015-02-28', u'2015-03-28', u'2015-04-28',
       u'2015-05-28', u'2015-06-28', u'2015-07-28', u'2015-08-28',
       u'2015-09-28', u'2015-10-28', u'2015-11-28', u'2015-12-28',
       u'2016-01-28', u'2016-02-28', u'2016-03-28', u'2016-04-28',
       u'2016-05-28'], dtype=object), 17)
('id', array([1375586, 1050617, 1050582, ..., 1166623, 1166617, 1166842], dtype=int64), 677181)
('employee_index', array([u'N', u'A', u'F', u'B', u'S'], dtype=object), 5)
('country_residence', array([u'ES', u'IT', u'BO', u'PY', u'DE'], dtype=object), 5)
('sex', array([u'H', u'V'], dtype=object), 2)
('age', array([  35.,   23.,   28.,   25.,   30.,   44.,   27.,   26.,   36.,
         22.,   33.,   24.,   32.,   37.,   42.,   57.,   31.,   12.,
          6.,   77.,   29.,   54.,   52.,   59.,   46.,   39.,   43.,
         51.,   16.,   48.,   40.,   53.,   73.,   47.,   34.,   17.,
         96.,   49.,   79.,    8.,   11.,   86.,   58.,    9.,   63.,
         64.,   50.,   

In [9]:
df = df_clean

from sklearn import preprocessing
le = preprocessing.LabelEncoder()
feature_cols =['date', 'id', 'employee_index', 'country_residence', 'sex', 'age',
       'first_join_date', 'new_customer_index', 'seniority', 'primary',
       'customer_type', 'customer_relation', 'residence_idx', 'foreigner_idx',
       'channel', 'deceased', 'address', 'province_code', 'province_name',
       'activity_idx', 'gross_income', 'segment']

feature_category_cols = feature_cols
feature_category_cols.remove('id')
feature_category_cols.remove('age')
feature_category_cols.remove('primary')
feature_category_cols.remove('activity_idx')
feature_category_cols.remove('customer_type')
feature_category_cols.remove('province_code')
feature_category_cols.remove('address')
feature_category_cols.remove('gross_income')
print(feature_category_cols)
for ind, feature_col in enumerate(feature_category_cols):
    le.fit(df[feature_col]) 
    df[feature_col]=le.transform(df[feature_col])

['date', 'employee_index', 'country_residence', 'sex', 'first_join_date', 'new_customer_index', 'seniority', 'customer_relation', 'residence_idx', 'foreigner_idx', 'channel', 'deceased', 'province_name', 'segment']


In [10]:

df.columns

Index([u'date', u'id', u'employee_index', u'country_residence', u'sex', u'age',
       u'first_join_date', u'new_customer_index', u'seniority', u'primary',
       u'customer_type', u'customer_relation', u'residence_idx',
       u'foreigner_idx', u'channel', u'deceased', u'address', u'province_code',
       u'province_name', u'activity_idx', u'gross_income', u'segment',
       u'saving_account', u'guarantees', u'current_account',
       u'derivada_account', u'payroll_account', u'junior_account',
       u'mas_particular_account', u'particular_account',
       u'particular_plus_account', u'short-term_deposits',
       u'medium-term_deposits', u'long-term_deposits', u'e-account', u'funds',
       u'mortgage', u'pensions', u'loans', u'taxes', u'credit_card',
       u'securities', u'home_account', u'payroll', u'pensions_1',
       u'direct_debit'],
      dtype='object')

In [11]:
df_encoder = df
df.columns
#cols_to_transform = [ 'date','employee_index', 'country_residence', 'first_join_date', 'sex', 
#'customer_type', 'customer_relation', 'residence_idx', 'foreigner_idx','channel', 'deceased','province_name','segment' ]

#df_with_dummies = pd.get_dummies(df, columns = cols_to_transform )
#df_with_dummies.head()
#df2 = df.drop(cols_to_transform, axis=1)

#len(df2)
df2 = df
df2.drop('id', axis =1)
len(df2)

2158888

#Setting up the Data

**Set up our data for our Random Forest Classification Model**


In [17]:
from sklearn.model_selection import train_test_split
target_cols =['saving_account',
       'guarantees', 'current_account', 'derivada_account', 'payroll_account',
       'junior_account', 'mas_particular_account', 'particular_account',
       'particular_plus_account', 'short-term_deposits',
       'medium-term_deposits', 'long-term_deposits', 'e-account', 'funds',
       'mortgage', 'pensions', 'loans', 'taxes', 'credit_card', 'securities',
       'home_account', 'payroll', 'pensions_1', 'direct_debit']
X = df2.drop(target_cols,axis=1)

import time

for target_col in target_cols:
    start_time = time.time()
    #y = df2['taxes']
    y = df2[target_col]
    #y = df2[target_cols]
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30)#, random_state=101)
    from sklearn.ensemble import RandomForestClassifier
    rfc = RandomForestClassifier(n_estimators=100)
    rfc.fit(X_train,y_train)
    predictions = rfc.predict(X_test)
    from sklearn.metrics import classification_report,confusion_matrix
    print("=================result for ",target_col)
    print(confusion_matrix(y_test,predictions))
    print(classification_report(y_test,predictions))

    print("--- %s seconds ---" % ((time.time() - start_time)/60.) )

('=================result for ', 'saving_account')
[[647601      0]
 [    38     28]]
             precision    recall  f1-score   support

          0       1.00      1.00      1.00    647601
          1       1.00      0.42      0.60        66

avg / total       1.00      1.00      1.00    647667

--- 5.82118333181 seconds ---
('=================result for ', 'guarantees')
[[647650      0]
 [     5     12]]
             precision    recall  f1-score   support

          0       1.00      1.00      1.00    647650
          1       1.00      0.71      0.83        17

avg / total       1.00      1.00      1.00    647667

--- 4.9501000007 seconds ---
('=================result for ', 'current_account')
[[168970  53879]
 [ 30091 394727]]
             precision    recall  f1-score   support

          0       0.85      0.76      0.80    222849
          1       0.88      0.93      0.90    424818

avg / total       0.87      0.87      0.87    647667

--- 16.374150002 seconds ---
('==========